import argparse
import subprocess
from subprocess import PIPE
import tempfile
from pathlib import Path
import re

class TESTS:

    @staticmethod
    def count_words(args):
        check_passed = True
        if args.shell_string.startswith('"') and args.shell_string.endswith('"'):
            args.shell_string = args.shell_string[1:-1]
        command = ["sh", "-c", args.shell_string]
        print(f"Counting words generated by shell command '{args.shell_string}'")
        result_raw = subprocess.run(command, stdout=PIPE, stderr=PIPE)
        # print(result_raw.stdout)
        for raw_search in args.expected.split(","):
            word, count = raw_search.split(":")
            count = int(count)
            search_count = len(re.findall(fr"{word}[\s,$]", result_raw.stdout.decode("utf-8")))
            if search_count != count:
                check_passed = False
                print(f"Expected '{word}' to appear {count}, but was only found {search_count}")
        # print(result_raw.stdout)
        # print(result_raw.stderr)
        return check_passed

    @staticmethod
    def temp_folder_run(args):
        if args.shell_string.startswith('"') and args.shell_string.endswith('"'):
            args.shell_string = args.shell_string[1:-1]
        print(f"Running shell command '{args.shell_string}' in temp folder")
        command = ["sh", "-c", args.shell_string]
        with tempfile.TemporaryDirectory() as dir_name:
            result_raw = subprocess.run(command, cwd=dir_name)
        return True


    @staticmethod
    def count_files(args):
        with tempfile.TemporaryDirectory() as dir_name:
            dir_name = Path(dir_name)
            if args.arguments.startswith('"') and args.arguments.endswith('"'):
                args.arguments = args.arguments[1:-1]
            command = [args.executable] + args.arguments.split(" ")
            print(f"Counting '{args.name}' generated by '{' '.join(command)}'")
            subprocess.run(command, cwd=dir_name)
            file_list = list(dir_name.rglob(f"**/{args.name}"))
            if args.arguments2 is not None:
                if args.arguments2.startswith('"') and args.arguments2.endswith('"'):
                    args.arguments2 = args.arguments2[1:-1]
                command2 = [args.executable] + args.arguments2.split(" ")
                if len(file_list) == 1:
                    command2.append(f"-D={file_list[0].parent.absolute()}")
                print(f"and '{' '.join(command2)}'")
                subprocess.run(command2)
                file_list = list(dir_name.rglob(f"**/{args.name}"))
            result = len(file_list)
        if result == args.expected:
            print(f"{args.expected} files where generated:")
            print("\t"+"\n\t".join([str(f) for f in file_list]))
            return True
        print(f"Expected {args.expected} but {result} files where generated:")
        if file_list:
            print("\t"+"\n\t".join([str(f) for f in file_list]))
        return False


if __name__ == '__main__':
    # MAIN PASER
    shared_parser = argparse.ArgumentParser(add_help=False)
    shared_parser.add_argument('-e', '--executable', type=str)
    parser = argparse.ArgumentParser(prog='external_unit_tests', parents=[shared_parser])
    action_parser = parser.add_subparsers(dest='action')

    # ACTION count_files
    parser_count_files = action_parser.add_parser('count_files', parents=[shared_parser])
    parser_count_files.add_argument('--expected', type=int)
    parser_count_files.add_argument('--name', type=str, default="aflow.in")
    parser_count_files.add_argument('--arguments', type=str)
    parser_count_files.add_argument('--arguments2', type=str, default=None)

    # ACTION count_words
    parser_count_files = action_parser.add_parser('count_words', parents=[shared_parser])
    parser_count_files.add_argument('--expected', type=str)
    parser_count_files.add_argument('--shell_string', type=str)

    # ACTION temp_folder_run
    parser_count_files = action_parser.add_parser('temp_folder_run', parents=[shared_parser])
    parser_count_files.add_argument('--shell_string', type=str)


    args = parser.parse_args()

    check_passed = False
    if not args.action:
        exit(2)
    if hasattr(TESTS, args.action):
        check_passed = getattr(TESTS, args.action)(args)
    if check_passed:
        exit(0)
    else:
        exit(1)



